### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by chrisapl** [timewasted/Search-SphinxsearchBundle#1]
Could you please provide a usage exampled of how to use bundle once configured to conduct a search from within a Symfony2 controller?

**Comment by timewasted** [comment]
Your basic search is simply:

``` php
$indexesToSearch = array(
  'Items' => array(),
  'Categories' => array(),
);
$sphinxSearch = $this->get('search.sphinxsearch.search');
$searchResults = $sphinxSearch->search('search query', $indexesToSearch);
```

That performs a search for `search query` against the indexes labeled `Items` and `Categories` with whatever defaults that are defined (both here and in your `sphinx.conf`).

If you want to do more than your basic search, it would look something like:

``` php
$indexesToSearch = array(
  'Items' => array(
    'result_offset' => 0,
    'result_limit' => 25,
  ),
  'Categories' => array(
    'result_offset' => 0,
    'result_limit' => 10,
  ),
);
$sphinxSearch = $this->get('search.sphinxsearch.search');
$sphinxSearch->setMatchMode(SPH_MATCH_EXTENDED);
$sphinxSearch->setFilter('disabled', array(1), true);
$searchResults = $sphinxSearch->search('search query', $indexesToSearch);
```

This would again search `Items` and `Categories` for `search query`, but now `Items` will return the first 25 matches, and `Categories` will return the first 10.  In order to define a `result_offset` or a `result_limit`, you must explicitly define both values.  Also, this will use the [Extended matching mode](http://sphinxsearch.com/docs/2.0.4/extended-syntax.html), and exclude all results with a `disabled` attribute set to `1`.

**Comment by chrisapl** [comment]
Thanks mate. Works a treat was just a little confused.

Cheers
Chris
